name: Update the daily fortune cookie

on:
  schedule:
    # This cron expression means it will run at midnight every day
    - cron: '0 0 * * *'
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  ACTIONS_STEP_DEBUG: true

jobs:
  update-fortune:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fortune-mod fortunes

    - name: Set Up PATH
      run: echo "${PATH}:/usr/games" >> $GITHUB_ENV

    - name: Run Fortune Update Script
      run: |
        go run scripts/update_fortune.go

    - name: Commit Changes
      run: |
        set -x
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add README.md
        git commit -m "Update fortune cookie"
        git push origin main|| "echo Couldnt push to github"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
