name: Update the daily fortune cookie

on:
  schedule:
    - cron: '0 0 * * *'  # At midnight every day
  workflow_dispatch:

env:
  FORTUNES: computers linux linuxcookie

jobs:
  update-fortune:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fortune-mod fortunes

    - name: Run Fortune Update Script
      run: |
        go run scripts/update_fortune.go ${{env.FORTUNES}}

    - name: Commit Changes
      run: |
        git config --local user.email "johannes@stenmark.in"
        git config --local user.name "JStenmark"
        git add README.md
        git commit -m "Update fortune cookie"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
